"""PPT 生成器 — 生成 .pptx 文件"""
from pathlib import Path
from . import BaseGenerator


class PptGenerator(BaseGenerator):
    supported_types = ["ppt"]

    async def generate(self, content: str, output_path: Path,
                       title: str = "", **kwargs) -> dict:
        self._ensure_dir(output_path)

        try:
            return await self._gen_pptx(content, output_path, title)
        except ImportError:
            return await self._gen_html_ppt(content, output_path, title)

    async def _gen_pptx(self, content: str, output_path: Path,
                         title: str) -> dict:
        """使用 python-pptx 生成 PPT"""
        from pptx import Presentation
        from pptx.util import Inches, Pt

        prs = Presentation()
        prs.slide_width = Inches(10)
        prs.slide_height = Inches(7.5)

        # 标题页
        slide_layout = prs.slide_layouts[0]  # Title Slide
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = title or "Presentation"
        if len(slide.placeholders) > 1:
            slide.placeholders[1].text = "Generated by Dream OS"

        # 内容页
        lines = content.strip().split("\n")
        current_slide_lines = []
        slides_content = []

        for line in lines:
            line = line.strip()
            if not line:
                continue
            # 以标题开头的行作为新 slide 的开始
            if line.startswith("# ") and current_slide_lines:
                slides_content.append(current_slide_lines)
                current_slide_lines = [line]
            else:
                current_slide_lines.append(line)
                # 每6行一页
                if len(current_slide_lines) >= 6:
                    slides_content.append(current_slide_lines)
                    current_slide_lines = []

        if current_slide_lines:
            slides_content.append(current_slide_lines)

        # 生成内容页
        slide_layout = prs.slide_layouts[1]  # Title and Content
        for page_lines in slides_content:
            slide = prs.slides.add_slide(slide_layout)
            page_title = page_lines[0].lstrip("# ").strip() if page_lines else ""
            page_content = "\n".join(page_lines[1:] if page_title else page_lines)

            slide.shapes.title.text = page_title[:50]
            if len(slide.placeholders) > 1:
                slide.placeholders[1].text = page_content[:800]

        prs.save(output_path)
        return {"success": True}

    async def _gen_html_ppt(self, content: str, output_path: Path,
                             title: str) -> dict:
        """降级：生成 HTML 格式的演示文稿"""
        html_path = output_path.with_suffix(".html")
        lines = content.strip().split("\n")

        slides_html = []
        current_lines = []
        for line in lines:
            line = line.strip()
            if not line:
                continue
            if line.startswith("# ") and current_lines:
                slides_html.append(current_lines)
                current_lines = [line]
            else:
                current_lines.append(line)
                if len(current_lines) >= 6:
                    slides_html.append(current_lines)
                    current_lines = []
        if current_lines:
            slides_html.append(current_lines)

        slides = ""
        for i, page in enumerate(slides_html):
            pt = page[0].lstrip("# ") if page else ""
            body = "<br>".join(p.lstrip("# ").replace("#", "") for p in (page[1:] if pt else page))
            slides += f'''<div class="slide"><h2>{pt}</h2><div class="body">{body}</div></div>'''

        html = f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>{title or 'Presentation'}</title>
<style>
body{{margin:0;background:#0a0a14;display:flex;flex-direction:column;align-items:center;padding:20px}}
.slide{{width:960px;height:540px;background:#1a1a2e;border-radius:12px;padding:40px;
margin:20px 0;box-shadow:0 4px 30px rgba(108,92,231,0.1)}}
.slide h2{{color:#6c5ce7;font-size:28px;margin-bottom:20px}}
.slide .body{{color:#e8e8f0;font-size:18px;line-height:1.8}}
@media print{{.slide{{page-break-after:always;margin:0;border-radius:0}}}}
</style></head><body>
<h1 style="color:#6c5ce7;font-size:36px">{title or 'Presentation'}</h1>
{slides}
</body></html>"""

        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)
        return {"success": True, "fallback": "html_slides"}
